### ISSUE TITLE
Predict two images

### ISSUE THREAD

**Issue by wduo** [mangye16/ReID-Survey#4]
Hello.
I want to know the similarity of two images.
Your code is the evaluation output.
I want to know the code to predict.
E.g. Given two image inputs
Can you tell if this is the same or not?
Or get each features?

**Comment by wduo** [comment]
@mangye16

**Comment by mangye16** [comment]
Hi,

Generally, the person re-identification is considered as a retrieval task, i.e., a retrieved list is output according to the similarity scores between the gallery images and query image.

If you want to predict two images belong to the same identity or not, you may need to train an additional classifier, for example, a similarity threshold. Alternatively, you may also mannually set the similarity threshold by extracting the features from the pooling layer output. 
I
