### ISSUE TITLE
self.inter_channels in non_local.py

### ISSUE THREAD

**Issue by TongYoungG** [mangye16/ReID-Survey#7]
作者，你好！

我发现 **non_local.py** 中的 **self.inter_channels** 的计算方式如下：
![288RI Q5P Q@7_3@2VEM9GK](https://user-images.githubusercontent.com/6924670/87912615-4508bc80-caa0-11ea-9fb4-0e4272d1302e.png)

但是原论文中应该是：self.inter_channels = in_channels // reduc_ratio

请问这是特意这样设置的吗，如果是的话，是基于什么样的理由呢？

**Comment by Hellomodo** [comment]
这里是我无意中将inter_channels设置成了1。
你可以按原文设置成self.inter_channels = in_channels // reduc_ratio，提高一些计算量，应该也能取得更好的效果，

**Comment by TongYoungG** [comment]
好的，谢谢！
